spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://stackexplode.cloud:13306/mall_wms?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: abc123
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: stackexplode.cloud:18848
  application:
    name: ware-service
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8085