spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://centos.stackexplode.cloud:13306/mall_wms?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: abc123
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: centos.stackexplode.cloud:18848
  application:
    name: ware-service
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-enums-package: cloud.stackexplode.gulimall.common.constant
server:
  port: 8085
logging:
  file: E:\Javaprojects\guli-mall\.logs\product-service.log
  level:
    org.zalando.logbook: trace
logbook:
  exclude:
    - "**.html"
    - "**.htm"
    - "**.js"
    - "**.css"
    - "**.jpg"
    - "**.ico"
    - "/static/**"