spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://stackexplode.cloud:13306/mall_pms?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: abc123
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: stackexplode.cloud:18848
  application:
    name: product-service
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8083
logging:
  file: product-service.log
  level:
    cloud.stackexplode.gulimall: debug
