spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://centos.stackexplode.cloud:13306/mall_pms?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: abc123
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: centos.stackexplode.cloud:18848
  application:
    name: product-service
  task:
    execution:
      pool:
        core-size: 6
        max-size: 12
        queue-capacity: 36
  jackson:
    date-format: yyyy-MM-dd HH-mm-ss
  redis:
    host: stackexplode.cloud
    port: 16379
    timeout: 1000ms
  data:
    redis:
      repositories:
        enabled: true
  cache:
    type: redis
    redis:
      time-to-live: 36000ms
mybatis-plus:
  type-enums-package: cloud.stackexplode.gulimall.common.constant
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8083
logging:
  file: E:\Javaprojects\guli-mall\.logs\product-service.log
  level:
    org.zalando.logbook: trace
logbook:
  exclude:
    - "**.html"
    - "**.htm"
    - "**.js"
    - "**.css"
    - "**.jpg"
    - "**.ico"
    - "/static/**"
