spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.7:3306/mall_oms?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: abc123
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: 192.168.1.7
  application:
    name: order-service
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8082