spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://centos.stackexplode.cloud:13306/mall_oms?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: abc123
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: centos.stackexplode.cloud:18848

  application:
    name: order-service
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8082
logging:
  file: E:\Javaprojects\guli-mall\.logs\order-service.log
  level:
    org.zalando.logbook: trace
logbook:
  exclude:
    - "**.html"
    - "**.htm"
    - "**.js"
    - "**.css"
    - "**.jpg"
    - "**.ico"
    - "/static/**"