spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://stackexplode.cloud:13306/mall_ums?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: abc123
  application:
    name: member-service
  cloud:
    nacos:
      discovery:
        server-addr: stackexplode.cloud:18848
        enabled: true
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8081
logging:
  file: E:\Javaprojects\guli-mall\.logs\member-service.log
  level:
    org.zalando.logbook: trace
logbook:
  exclude:
    - "**.html"
    - "**.htm"
    - "**.js"
    - "**.css"
    - "**.jpg"
    - "**.ico"
    - "/static/**"
