server:
  port: 10086
spring:
  jackson:
    date-format: yyyy-MM-dd HH-mm-ss
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: centos.stackexplode.cloud:18848
        enabled: true
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payment/**
          filters:
            - RewritePath=/api(?<path>.*), $\{path}
        - id: shoppingcart-service
          uri: lb://shoppingcart-service
          predicates:
            - Path=/api/shoppingcart/**
          filters:
            - RewritePath=/api(?<path>.*), $\{path}
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api(?<path>.*), $\{path}
        - id: search-service
          uri: lb://search-service
          predicates:
            - Path=/api/search/**
          filters:
            - RewritePath=/api(?<path>.*), $\{path}
        - id: product
          uri: lb://product-service
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api(?<path>.*), $\{path}
        - id: coupon
          uri: lb://coupon-service
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api(?<path>/?.*), $\{path}
        - id: member
          uri: lb://member-service
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api(?<path>/?.*), $\{path}
        - id: order
          uri: lb://order-service
          predicates:
            - Path=/api/order/**
          filters:
            - RewritePath=/api(?<path>/?.*), $\{path}
        - id: ware
          uri: lb://ware-service
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api(?<path>/?.*), $\{path}
        - id: oss
          uri: lb://oss-service
          predicates:
            - Path=/api/oss/**
          filters:
            - RewritePath=/api(?<path>/?.*), $\{path}
        - id: renren-fast
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api(?<path>/?.*), $\{path}
logging:
  file: E:\Javaprojects\guli-mall\.logs\gateway-service.log
  level:
    web: trace
    org.springframework.web: trace
    org.springframework.http: trace
    org.springframework.cloud.gateway: trace
    org.springframework.cloud.gateway.filter: trace
    org.springframework.cloud.gateway.handler: trace
    org.springframework.cloud.gateway.route: trace
    org.springframework.cloud.gateway.support: trace
    org.springframework.cloud.gateway.support.ipresolver: trace
    org.springframework.cloud.gateway.support.server: trace