server:
  port: 10086
spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      discovery:
        server-addr: centos.stackexplode.cloud:18848
        enabled: true
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600
            preflightMaxAge: 86400
      routes:
        - id: search-service
          uri: lb://search-service
          predicates:
            - Path=/api/search/**
          filters:
            - RewritePath=/api(?<path>.*), /$\{path}
        - id: product
          uri: lb://product-service
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api(?<path>.*), /$\{path}
        - id: coupon
          uri: lb://coupon-service
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api(?<path>/?.*), $\{path}
        - id: member
          uri: lb://member-service
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api(?<path>/?.*), $\{path}
        - id: order
          uri: lb://order-service
          predicates:
            - Path=/api/order/**
          filters:
            - RewritePath=/api(?<path>/?.*), $\{path}
        - id: ware
          uri: lb://ware-service
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api(?<path>/?.*), $\{path}
        - id: oss
          uri: lb://oss-service
          predicates:
            - Path=/api/oss/**
          filters:
            - RewritePath=/api(?<path>/?.*), $\{path}
        - id: renren-fast
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api(?<path>/?.*), $\{path}
logging:
  file: E:\Javaprojects\guli-mall\.logs\gateway-service.log
  level:
    org.zalando.logbook: trace
logbook:
  exclude:
    - "**.html"
    - "**.htm"
    - "**.js"
    - "**.css"
    - "**.jpg"
    - "**.ico"
    - "/static/**"
