server:
  port: 8086
spring:
  jackson:
    date-format: yyyy-MM-dd HH-mm-ss
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  cloud:
    nacos:
      discovery:
        server-addr: centos.stackexplode.cloud:18848
  application:
    name: oss-service

logging:
  file: E:\Javaprojects\guli-mall\.logs\oss-service.log
