server:
  port: 8086
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  cloud:
    nacos:
      discovery:
        server-addr: stackexplode.cloud:18848
  application:
    name: oss-service

logging:
  file: E:\Javaprojects\guli-mall\.logs\oss-service.log
  level:
    org.zalando.logbook: trace
logbook:
  exclude:
    - "**.html"
    - "**.htm"
    - "**.js"
    - "**.css"
    - "**.jpg"
    - "**.ico"
    - "/static/**"