server:
  port: 8086
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  cloud:
    nacos:
      discovery:
        server-addr: stackexplode.cloud:18848
  application:
    name: oss-service
logging:
  file: oss-service.log
  level:
    cloud.stackexplode.gulimall: debug
