server:
  port: 8091
spring:
  jackson:
    date-format: yyyy-MM-dd HH-mm-ss
  thymeleaf:
    cache: false
  session:
    redis:
      namespace: spring:session
      flush-mode: immediate
    servlet:
      filter-order: 1
    timeout: 1800
  application:
    name: auth-service
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: centos.stackexplode.cloud:18848
  task:
    execution:
      pool:
        core-size: 6
        max-size: 6
  redis:
    host: centos.stackexplode.cloud
    port: 16379
logging:
  file:
    path: E:\Javaprojects\guli-mall\.logs\auth-service.log
