spring:
  datasource:
    url: jdbc:mysql://192.168.1.7:3306/mall_sms?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: abc123
    driverClassName: com.mysql.cj.jdbc.Driver
  application:
    name: coupon-service
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: 192.168.1.7

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8080