spring:
  datasource:
    url: jdbc:mysql://stackexplode.cloud:13306/mall_sms?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: abc123
    driverClassName: com.mysql.cj.jdbc.Driver
  application:
    name: coupon-service
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: stackexplode.cloud:18848

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8080