spring:
  jackson:
    date-format: yyyy-MM-dd HH-mm-ss
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: centos.stackexplode.cloud:18848
      config:
        enabled: true
        file-extension: properties
        name: search-service
        server-addr: centos.stackexplode.cloud:18848
  application:
    name: search-service
  data:
    redis:
      repositories:
        enabled: true
  session:
    redis:
      namespace: spring:session
      flush-mode: immediate
  redis:
    host: centos.stackexplode.cloud
    port: 16379
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    suffix: .html
    prefix: classpath:/templates/
server:
  port: 8087
logging:
  level:
    org.springframework.data.elasticsearch: TRACE
  file:
    name: E:\Javaprojects\guli-mall\.logs\search-service.log